### ISSUE TITLE
Update required circuits_i2c version

### ISSUE THREAD

**Issue by krns** [jjcarstens/sgp30#13]
Hi, I just started building the weather station according to this book: https://pragprog.com/titles/passweather/build-a-weather-station-with-elixir-and-nerves/

I would like to use up to date version of the dependencies and discovered that this library is not ready for the latest circuits_i2c version (1.0.1) because of the version constraint `{:circuits_i2c, "~> 0.3"}`.

The [release notes](https://github.com/elixir-circuits/circuits_i2c/releases) of circuits_i2c look like there are no breaking changes. What do you think updating the version constraint to support the latest circuits_i2c version?

**Comment by krns** [comment]
Just updated the comment.. accidentally pressed enter while creating the issue >.>

**Comment by jjcarstens** [comment]
Published https://hex.pm/packages/sgp30/0.2.2

**Comment by krns** [comment]
Thanks!
